### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by XVincentX** [OlliV/micri#15]
Apparently the package is using other packages that aren't listed in its dependencies; at the same time, the readme is not mentioning any of these and so when you do even the most basic application you receive a crash as a welcome.

**Comment by OlliV** [comment]
The dependencies are bundled in the package using [zeit/ncc](https://github.com/zeit/ncc). Can you post an example where you are seeing a crash because it shouldn't be related to the dependencies?

**Comment by XVincentX** [comment]
It works after installing the types.

**Comment by OlliV** [comment]
Thanks for the update.

**Comment by XVincentX** [comment]
You might want to mention it in the readme though
