### ISSUE TITLE
Try to squeeze the deps

### ISSUE THREAD

**Issue by OlliV** [OlliV/micri#2]
`raw-body` depends on `iconv-lite` which is 93% of the install size of this package, is it really needed for something?

**Comment by OlliV** [comment]
This is pretty much fine now and it's very hard to squeeze it anymore.

**Comment by amio** [comment]
@OlliV Can we upgrade `raw-body` to latest `2.4.1`？ Which depends on `iconv-lite@0.4.24`, which [fixed](https://github.com/ashtuchkin/iconv-lite/pull/185) an annoying deprecation warning on Node.js v10:

```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by OlliV** [comment]
oh for sure.

**Comment by OlliV** [comment]
@amio This bumps it https://github.com/OlliV/micri/releases/tag/2.0.1
